name: angular_components
version: 1.0.3
description: >
  The official Material Design components for AngularDart. Used at Google in
  production apps.
repository: https://github.com/angulardart/angular_components

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_forms: ^4.0.1
  async: ^2.1.0
  build: ^2.1.0
  build_config: ^1.0.0
  built_collection: ^4.0.0
  collection: ^1.14.10
  fixnum: ^0.10.7
  intl: ^0.16.0
  js: ^0.6.1
  logging: ^1.0.2
  meta: ^1.0.4
  observable: ^0.23.0
  protobuf: ^1.0.0
  quiver: ^3.0.0
  sass_builder: ^2.0.2

dev_dependencies:
  path: ^1.6.1
  pedantic: ^1.8.0
  test: ^1.0.0
